
spring.servlet.multipart.max-file-size : 10Mb
spring.http.multipart.max-request-size : 100Mb

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1/spring_boot?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driveClassName: com.mysql.jdbc.Driver
    username: root
    password: tianxiadiyi55
    type: com.alibaba.druid.pool.DruidDataSource

mybais:
configuration:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.fzm.boot.model.po.*
  mapUnderscoreToCamelCase: true